#include "efload_port.h"

/*
 * Copy this file to Core/Src/efload_port.c in a CubeMX project, then replace
 * the TODO sections with handles and GPIO names generated by CubeMX.
 */

#include "board.h"
#include "config_default.h"

/*
 * TODO: enable these includes in the CubeMX project after the matching
 * peripherals are generated.
 *
 * #include "adc.h"
 * #include "dma.h"
 * #include "gpio.h"
 * #include "main.h"
 * #include "tim.h"
 */

supervisor_t g_efload_supervisor;

static uint16_t s_adc_dma_buffer[EFLOAD_ADC_CHANNEL_COUNT];

static float adc_count_to_pin_v(uint16_t raw)
{
    return ((float)raw / EFLOAD_BOARD_ADC_FULL_SCALE_COUNT) * EFLOAD_BOARD_ADC_REF_V;
}

static float adc_read_bipolar(uint32_t index, float gain, float sign)
{
    const float pin_v = adc_count_to_pin_v(s_adc_dma_buffer[index]);
    return (pin_v - EFLOAD_BOARD_ADC_BIPOLAR_MID_V) * gain * sign;
}

static float adc_read_unipolar(uint32_t index, float gain)
{
    const float pin_v = adc_count_to_pin_v(s_adc_dma_buffer[index]);
    return pin_v * gain;
}

static bool port_adc_read(hal_adc_frame_t *frame, void *context)
{
    (void)context;

    if (frame == 0) {
        return false;
    }

    frame->cvcf_phase_voltage_v.a =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_VA, EFLOAD_GAIN_CVCF_VA_V_PER_V, EFLOAD_SIGN_CVCF_VA);
    frame->cvcf_phase_voltage_v.b =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_VB, EFLOAD_GAIN_CVCF_VB_V_PER_V, EFLOAD_SIGN_CVCF_VB);
    frame->cvcf_phase_voltage_v.c =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_VC, EFLOAD_GAIN_CVCF_VC_V_PER_V, EFLOAD_SIGN_CVCF_VC);

    frame->cvcf_phase_current_a.a =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_IA, EFLOAD_GAIN_CVCF_IA_A_PER_V, EFLOAD_SIGN_CVCF_IA);
    frame->cvcf_phase_current_a.b =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_IB, EFLOAD_GAIN_CVCF_IB_A_PER_V, EFLOAD_SIGN_CVCF_IB);
    frame->cvcf_phase_current_a.c =
        adc_read_bipolar(EFLOAD_ADC_IDX_CVCF_IC, EFLOAD_GAIN_CVCF_IC_A_PER_V, EFLOAD_SIGN_CVCF_IC);

    frame->rectifier_phase_voltage_v.a =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_VA, EFLOAD_GAIN_RECT_VA_V_PER_V, EFLOAD_SIGN_RECT_VA);
    frame->rectifier_phase_voltage_v.b =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_VB, EFLOAD_GAIN_RECT_VB_V_PER_V, EFLOAD_SIGN_RECT_VB);
    frame->rectifier_phase_voltage_v.c =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_VC, EFLOAD_GAIN_RECT_VC_V_PER_V, EFLOAD_SIGN_RECT_VC);

    frame->rectifier_phase_current_a.a =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_IA, EFLOAD_GAIN_RECT_IA_A_PER_V, EFLOAD_SIGN_RECT_IA);
    frame->rectifier_phase_current_a.b =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_IB, EFLOAD_GAIN_RECT_IB_A_PER_V, EFLOAD_SIGN_RECT_IB);
    frame->rectifier_phase_current_a.c =
        adc_read_bipolar(EFLOAD_ADC_IDX_RECT_IC, EFLOAD_GAIN_RECT_IC_A_PER_V, EFLOAD_SIGN_RECT_IC);

    frame->dc_bus_v = adc_read_unipolar(EFLOAD_ADC_IDX_DC_BUS, EFLOAD_GAIN_DC_BUS_V_PER_V);
    return true;
}

static uint32_t duty_to_compare(float duty, uint32_t period_counts)
{
    if (duty < 0.0f) {
        duty = 0.0f;
    }
    if (duty > 1.0f) {
        duty = 1.0f;
    }
    return (uint32_t)(duty * (float)period_counts);
}

static bool port_pwm_update(const hal_pwm_duties_t *duties, void *context)
{
    (void)context;

    if (duties == 0) {
        return false;
    }

    /*
     * TODO: replace with the actual CubeMX timer handles and channels.
     *
     * const uint32_t cvcf_period = __HAL_TIM_GET_AUTORELOAD(&htim1);
     * __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, duty_to_compare(duties->cvcf.a, cvcf_period));
     * __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_2, duty_to_compare(duties->cvcf.b, cvcf_period));
     * __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_3, duty_to_compare(duties->cvcf.c, cvcf_period));
     *
     * const uint32_t rect_period = __HAL_TIM_GET_AUTORELOAD(&htim8);
     * __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_1, duty_to_compare(duties->rectifier.a, rect_period));
     * __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_2, duty_to_compare(duties->rectifier.b, rect_period));
     * __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_3, duty_to_compare(duties->rectifier.c, rect_period));
     */
    (void)duty_to_compare;
    return true;
}

static void port_pwm_enable(converter_id_t converter, bool enable, void *context)
{
    (void)converter;
    (void)enable;
    (void)context;

    /*
     * TODO: drive gate-enable GPIOs generated by CubeMX.
     *
     * if (converter == CONVERTER_CVCF_SOURCE) {
     *     HAL_GPIO_WritePin(CVCF_GATE_EN_GPIO_Port, CVCF_GATE_EN_Pin,
     *                       enable ? GPIO_PIN_SET : GPIO_PIN_RESET);
     * } else {
     *     HAL_GPIO_WritePin(RECT_GATE_EN_GPIO_Port, RECT_GATE_EN_Pin,
     *                       enable ? GPIO_PIN_SET : GPIO_PIN_RESET);
     * }
     */
}

static void port_pwm_disable(void *context)
{
    (void)context;

    /*
     * TODO: this must disable both power stages from any state.
     *
     * HAL_GPIO_WritePin(CVCF_GATE_EN_GPIO_Port, CVCF_GATE_EN_Pin, GPIO_PIN_RESET);
     * HAL_GPIO_WritePin(RECT_GATE_EN_GPIO_Port, RECT_GATE_EN_Pin, GPIO_PIN_RESET);
     *
     * Optional:
     * __HAL_TIM_MOE_DISABLE(&htim1);
     * __HAL_TIM_MOE_DISABLE(&htim8);
     */
}

static bool port_pwm_set_deadtime_ns(uint32_t deadtime_ns, void *context)
{
    (void)deadtime_ns;
    (void)context;

    /*
     * TODO: usually deadtime is configured by CubeMX before runtime.
     * Return false here if your port requires runtime deadtime and cannot set it.
     */
    return true;
}

static uint32_t port_timer_now_us(void *context)
{
    (void)context;

    /*
     * TODO: use a 1 MHz 32-bit timer or DWT-based microsecond counter.
     *
     * return __HAL_TIM_GET_COUNTER(&htim2);
     */
    return 0u;
}

static void port_gpio_set_led(bool on, void *context)
{
    (void)on;
    (void)context;

    /*
     * TODO:
     * HAL_GPIO_WritePin(STATUS_LED_GPIO_Port, STATUS_LED_Pin,
     *                   on ? GPIO_PIN_SET : GPIO_PIN_RESET);
     */
}

static bool port_gpio_read_estop(void *context)
{
    (void)context;

    /*
     * TODO:
     * return HAL_GPIO_ReadPin(ESTOP_GPIO_Port, ESTOP_Pin) == GPIO_PIN_SET;
     */
    return false;
}

static uint32_t port_protection_read_latched(void *context)
{
    (void)context;

    /*
     * TODO: collect driver fault, comparator fault, emergency stop, etc.
     *
     * uint32_t flags = HAL_PROTECTION_NONE;
     * if (HAL_GPIO_ReadPin(OC_FAULT_GPIO_Port, OC_FAULT_Pin) == GPIO_PIN_SET) {
     *     flags |= HAL_PROTECTION_OVERCURRENT;
     * }
     * return flags;
     */
    return HAL_PROTECTION_NONE;
}

static void port_protection_clear_latched(void *context)
{
    (void)context;

    /*
     * TODO: clear external latch or driver fault latch if your hardware provides
     * a reset pin. Do not clear faults automatically from RUN.
     */
}

void efload_port_init(void)
{
    supervisor_config_t config;
    supervisor_default_config(&config);

    config.ts = 1.0f / EFLOAD_BOARD_CONTROL_FREQUENCY_HZ;
    config.dc_bus_min_v = EFLOAD_BOARD_DC_BUS_MIN_V;
    config.dc_bus_max_v = EFLOAD_BOARD_DC_BUS_MAX_V;
    config.phase_current_limit_a = EFLOAD_BOARD_PHASE_CURRENT_LIMIT_A;

    const supervisor_io_t io = {
        .adc = {
            .read = port_adc_read,
            .context = 0,
        },
        .pwm = {
            .update_duties = port_pwm_update,
            .enable = port_pwm_enable,
            .disable = port_pwm_disable,
            .set_deadtime_ns = port_pwm_set_deadtime_ns,
            .context = 0,
        },
        .timer = {
            .now_us = port_timer_now_us,
            .context = 0,
        },
        .gpio = {
            .set_status_led = port_gpio_set_led,
            .read_estop = port_gpio_read_estop,
            .context = 0,
        },
        .protection = {
            .read_latched = port_protection_read_latched,
            .clear_latched = port_protection_clear_latched,
            .context = 0,
        },
    };

    supervisor_init(&g_efload_supervisor, &config, io);
    (void)port_pwm_set_deadtime_ns(EFLOAD_BOARD_PWM_DEADTIME_NS, 0);
}

void efload_port_start(void)
{
    supervisor_request_start(&g_efload_supervisor);
}

void efload_port_stop(void)
{
    supervisor_request_stop(&g_efload_supervisor);
}

void efload_port_clear_fault(void)
{
    supervisor_clear_fault(&g_efload_supervisor);
}

void efload_port_on_control_period(void)
{
    supervisor_on_pwm_period(&g_efload_supervisor);
}

