#ifndef EFLOAD_CONFIG_DEFAULT_H
#define EFLOAD_CONFIG_DEFAULT_H

#define EFLOAD_DEFAULT_FSW_HZ (20000.0f)
#define EFLOAD_DEFAULT_TS_S (1.0f / EFLOAD_DEFAULT_FSW_HZ)
#define EFLOAD_DEFAULT_GRID_HZ (50.0f)
#define EFLOAD_DEFAULT_VDC_MIN_V (40.0f)
#define EFLOAD_DEFAULT_VDC_MAX_V (70.0f)
#define EFLOAD_DEFAULT_VDC_NOMINAL_V (60.0f)
#define EFLOAD_DEFAULT_LINE_RMS_V (32.0f)
#define EFLOAD_DEFAULT_PHASE_CURRENT_LIMIT_A (3.0f)
#define EFLOAD_DEFAULT_LOAD_CURRENT_MAX_A (2.0f)
#define EFLOAD_DEFAULT_FILTER_L_H (0.001f)
#define EFLOAD_DEFAULT_FILTER_C_F (0.000010f)
#define EFLOAD_DEFAULT_DUTY_MIN (0.02f)
#define EFLOAD_DEFAULT_DUTY_MAX (0.98f)
#define EFLOAD_DEFAULT_PRECHARGE_US (100000u)
#define EFLOAD_DEFAULT_SYNC_MIN_LOCKED_TICKS (200u)

#endif

